"""New update

Revision ID: 7a0a55a27952
Revises: 7951bde73679
Create Date: 2025-06-01 16:20:08.157190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a0a55a27952'
down_revision: Union[str, None] = '7951bde73679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curso_materia', sa.Column('profesor_id', sa.Integer(), nullable=False))
    op.add_column('curso_materia', sa.Column('horario', sa.String(), nullable=True))
    op.add_column('curso_materia', sa.Column('aula', sa.String(), nullable=True))
    op.add_column('curso_materia', sa.Column('modalidad', sa.String(), nullable=True))
    op.alter_column('curso_materia', 'materia_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('curso_materia', 'curso_periodo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'curso_materia', 'profesores', ['profesor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'curso_materia', type_='foreignkey')
    op.alter_column('curso_materia', 'curso_periodo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('curso_materia', 'materia_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('curso_materia', 'modalidad')
    op.drop_column('curso_materia', 'aula')
    op.drop_column('curso_materia', 'horario')
    op.drop_column('curso_materia', 'profesor_id')
    # ### end Alembic commands ###
