"""Update periodo table with bimestre and anhioo

Revision ID: 8a7bcdb291f3
Revises: a2b00b9beceb
Create Date: 2025-06-01 15:11:21.120056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a7bcdb291f3'
down_revision: Union[str, None] = 'a2b00b9beceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periodo', sa.Column('bimestre', sa.Integer(), nullable=False))
    op.add_column('periodo', sa.Column('anio', sa.Integer(), nullable=False))
    op.alter_column('periodo', 'fecha_inicio',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('periodo', 'fecha_fin',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.drop_column('periodo', 'nombre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periodo', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('periodo', 'fecha_fin',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('periodo', 'fecha_inicio',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('periodo', 'anio')
    op.drop_column('periodo', 'bimestre')
    # ### end Alembic commands ###
