"""Add curso_materia table

Revision ID: a4cbcf546384
Revises: cf38da5a71fd
Create Date: 2025-06-01 15:26:03.341135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4cbcf546384'
down_revision: Union[str, None] = 'cf38da5a71fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso_materia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_periodo_id', sa.Integer(), nullable=True),
    sa.Column('materia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['curso_periodo_id'], ['curso_periodo.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curso_materia_id'), 'curso_materia', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curso_materia_id'), table_name='curso_materia')
    op.drop_table('curso_materia')
    # ### end Alembic commands ###
