"""Add curso_periodo_id to estudiantes

Revision ID: b2fd636af830
Revises: da40cf7350fa
Create Date: 2025-06-04 10:01:22.377483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2fd636af830'
down_revision: Union[str, None] = 'da40cf7350fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudiantes', sa.Column('curso_periodo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'estudiantes', 'curso_periodo', ['curso_periodo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estudiantes', type_='foreignkey')
    op.drop_column('estudiantes', 'curso_periodo_id')
    # ### end Alembic commands ###
