"""Add periodo, curso, and curso_periodo tables 2

Revision ID: bfe7cc49df6a
Revises: 60b9d4ffce36
Create Date: 2025-06-01 14:34:33.000582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe7cc49df6a'
down_revision: Union[str, None] = '60b9d4ffce36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('sigla', sa.String(), nullable=False),
    sa.Column('nivel', sa.String(), nullable=False),
    sa.Column('capacidad_maxima', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curso_id'), 'curso', ['id'], unique=False)
    op.create_table('periodo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periodo_id'), 'periodo', ['id'], unique=False)
    op.create_table('curso_periodo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=True),
    sa.Column('periodo_id', sa.Integer(), nullable=True),
    sa.Column('aula', sa.String(), nullable=True),
    sa.Column('turno', sa.String(), nullable=True),
    sa.Column('capacidad_actual', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curso_periodo_id'), 'curso_periodo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curso_periodo_id'), table_name='curso_periodo')
    op.drop_table('curso_periodo')
    op.drop_index(op.f('ix_periodo_id'), table_name='periodo')
    op.drop_table('periodo')
    op.drop_index(op.f('ix_curso_id'), table_name='curso')
    op.drop_table('curso')
    # ### end Alembic commands ###
