"""Add materia tables

Revision ID: cf38da5a71fd
Revises: 896d46ec64f1
Create Date: 2025-06-01 15:20:08.262052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf38da5a71fd'
down_revision: Union[str, None] = '896d46ec64f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('area_conocimiento', sa.String(), nullable=False),
    sa.Column('horas_semanales', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materia_id'), 'materia', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materia_id'), table_name='materia')
    op.drop_table('materia')
    # ### end Alembic commands ###
