"""Add participaciones, asistencia, and nota tables

Revision ID: da40cf7350fa
Revises: e593e62add4f
Create Date: 2025-06-01 22:21:31.789340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da40cf7350fa'
down_revision: Union[str, None] = 'e593e62add4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('curso_materia_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Boolean(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curso_materia_id'], ['curso_materia.id'], ),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asistencia_id'), 'asistencia', ['id'], unique=False)
    op.create_table('nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('curso_materia_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('rendimiento', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['curso_materia_id'], ['curso_materia.id'], ),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nota_id'), 'nota', ['id'], unique=False)
    op.create_table('participaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('curso_materia_id', sa.Integer(), nullable=False),
    sa.Column('participacion_clase', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('observacion', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['curso_materia_id'], ['curso_materia.id'], ),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participaciones_id'), 'participaciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participaciones_id'), table_name='participaciones')
    op.drop_table('participaciones')
    op.drop_index(op.f('ix_nota_id'), table_name='nota')
    op.drop_table('nota')
    op.drop_index(op.f('ix_asistencia_id'), table_name='asistencia')
    op.drop_table('asistencia')
    # ### end Alembic commands ###
