"""Add participaciones, asistencia, and nota tables

Revision ID: e593e62add4f
Revises: b9b035622d32
Create Date: 2025-06-01 22:12:37.931520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e593e62add4f'
down_revision: Union[str, None] = 'b9b035622d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
